import type { LegalDocumentContent } from "./legalContent.types";

export const PRIVACY_POLICY_CONTENT: LegalDocumentContent = {
  lastUpdated: "June 25, 2026",
  heroSubtitle:
    "How EdgeVerse collects, uses, protects, and manages personal information across our digital platforms.",
  introParagraphs: [
    'This Privacy Policy (the "Privacy Policy" or "Policy") establishes a legal and statutory framework governing how EdgeVerse India Private Limited (hereinafter referred to as the "Company", "we", "us", or "our") collects, processes, stores, retains, isolates, transfers, and commercializes data generated by or collected from any user, reader, browser, viewer, or corporate entity (hereinafter referred to as the "User" or "you") accessing or interacting with the website https://edgeverse.ai/ (the "Website") or utilizing any connected digital interfaces, marketing pipelines, or localized platforms.',
    "This Policy functions as a mandatory statutory notice to you. By continuing to access, browse, or fill out communication forms on the Website, you acknowledge that you have read this Policy and grant your free, specific, informed, unconditional, and unambiguous consent to the Company to process your personal data in accordance with the exhaustive terms set out below.",
  ],
  sections: [
    {
      title: "Comprehensive and Granular Categories of Data Collected",
      intro:
        "The Company does not merely collect static form text; we operate a sophisticated multi-layered digital architecture that captures user-disclosed info, background network identifiers, and localized file modifications. The datasets collected are categorized into three separate technical horizons:",
      subsections: [
        {
          title: "Active Data (Explicitly Disclosed Information)",
          intro:
            "This category encompasses all data packets that you intentionally, knowingly, and directly key into, upload, or transmit through the Website surface or communication gateways:",
          items: [
            {
              label: "Identity Profiles",
              text: "Full legal name, title, professional honorifics, corporate affiliations, and photographs or visual portraits if voluntarily appended to digital CVs, employment inquiries, or partner portal applications.",
            },
            {
              label: "Corporate Contact Credentials",
              text: "Corporate or personal electronic mail addresses, secondary backup email coordinates, active mobile phone numbers, landline extensions, and geographic or physical corporate addresses.",
            },
            {
              label: "Professional Demographics",
              text: "Current employer name, corporate registration data, job title, industry domain (including but not limited to Two-Wheeler Original Equipment Manufacturers [OEMs], Tier-1 automotive component suppliers, automated transit fleet operators, and logistics tech companies).",
            },
            {
              label: "Communications and Input Payload Logs",
              text: 'The exact contents, alphanumeric strings, text blocks, embedded attachments, project scopes, and background metadata contained within any "Get in Touch" forms, query boxes, or direct chat strings submitted to the Company.',
            },
          ],
        },
        {
          title: "Passive Data (Automated Technical, Network, and Server Logs)",
          intro:
            "The exact millisecond your device issues an HTTP or HTTPS request to our network infrastructure, our servers automatically establish a handshake and capture technical metadata emitted by your machine:",
          items: [
            {
              label: "Network and Routing Identifiers",
              text: "Your unique Internet Protocol (IP) address (whether static or dynamic), proxy server routes, Internet Service Provider (ISP) mapping configurations (e.g., Reliance Jio, Bharti Airtel, Vodafone Idea), and macro-geographic location matrices (resolved down to the country, state, and city level).",
            },
            {
              label: "Device and Environment Profiles",
              text: "Hardware model definitions, local operating system environments (e.g., Apple macOS, Microsoft Windows, iOS, Linux, Android), active screen resolution matrices, system language preferences, and full browser user-agent strings (e.g., Google Chrome, Apple Safari, Mozilla Firefox).",
            },
            {
              label: "Clickstream, Telemetry, and Interaction Metrics",
              text: "Comprehensive tracking of your navigation path through our site, specific URL timestamps, landing and exit pages, individual video playbacks or advanced simulation clips watched, scroll depth metrics, total session duration, and the specific search terms or external hyperlinks that redirected you to our Website.",
            },
          ],
        },
        {
          title: "Under-the-Hood Operations, Cache, and Browser Storage",
          intro:
            "To optimize network loading speeds, reduce latency for high-bandwidth media (such as ARAS technology recordings and road test demonstrations), and run analytical trackers, our Website forces data modifications on your local device storage:",
          items: [
            {
              label: "HTTP Cookies",
              text: "Small text fragments dropped onto your local hard drive. We utilize Session Cookies (which terminate instantly upon closing your browser tab to maintain active state transitions) and Persistent Analytical Cookies (which survive tab closures to identify if you are a returning visitor).",
            },
            {
              label: "The Browser Cache",
              text: "The Website commands your local browser application to download and save copies of the Company's proprietary assets including CSS style sheets, media fragments, custom font engines, vector graphics, and JavaScript scripts directly inside your device's local memory bank. While cache data does not map human identities on its own, it logs an immutable physical record of your interaction with our infrastructure on your hard drive.",
            },
            {
              label: 'HTML5 Local Storage ("Super-Cookies")',
              text: "Persistent data vaults inside your browser application that store long-term site configuration data (such as your choice to accept or decline cookie tracking) with no hardcoded expiration date. This data remains on your machine permanently until you manually clear your browser data.",
            },
            {
              label: "Tracking Pixels and Retargeting Tags",
              text: "Code lines (such as LinkedIn Insight Tags, Google Analytics tracking scripts, or Meta Pixels) that track your professional device profile across third-party networks, enabling the Company to analyze the reach of our B2B tech stack marketing campaigns.",
            },
          ],
        },
      ],
    },
    {
      title: "The Company's Unconditional Right to Use, Exploit, and Process Data",
      paragraphs: [
        "By interacting with this Website or submitting data through any of its portals, you hereby grant to the Company an unconditional, perpetual, non-exclusive, royalty-free, fully paid-up, worldwide, sub-licensable, and completely irrevocable right and license to collect, process, adapt, compile, index, analyze, modify, publish, transmit, and commercially exploit all data collected under Section 1 of this Policy.",
        "The Company is legally entitled to leverage, monetize, and deploy this data in whatsoever manner and in whatsoever way as desired by the Company, at its sole, absolute, and unreviewable discretion. This absolute right of exploitation includes, but is not limited to:",
      ],
      items: [
        "Fulfilling, updating, and executing B2B relationships, enterprise pilot programs, and product demonstrations.",
        "Diagnosing server errors, optimizing the visual delivery of our ARAS simulation architectures, and enhancing network security protocols.",
        "Training internal machine learning engines, refining computer vision models, optimizing the Perceiva™ software platform, and enhancing our proprietary edge-native India Perception Model.",
        "Commercializing high-level data trends or industry traffic safety models to automotive stakeholders without any requirement to provide an accounting, financial compensation, royalties, or individual notifications to you.",
      ],
    },
    {
      title: "Statutory Rights of the User",
      intro:
        "The Company recognizes and protects your non-waivable rights as a User. You can invoke these rights at any time by writing an official request to our designated Grievance channel:",
      items: [
        {
          label: "Right to Access and Summary",
          text: "You have the right to request a complete summary of all your personal data being processed by us, a description of the precise processing operations being executed, and the structural identities of any third-party Data Processors or Fiduciaries with whom your personal data has been shared.",
        },
        {
          label: "Right to Correction, Completion, and Updating",
          text: "You have the right to secure the immediate correction of any inaccurate personal data, the completion of any structurally incomplete records, and the updating of any obsolete data linked to your identity on our databases.",
        },
        {
          label: "Right to Erasure",
          text: "You have the right to demand the permanent deletion or erasure of your personal data when the specified purpose for which it was collected has been fully exhausted, or when you choose to withdraw your consent to our processing pipelines.",
        },
        {
          label: "Right to Nominate",
          text: "You have the right to formally nominate any other natural person to exercise your data protection rights in the event of your death, physical injury, or mental incapacity.",
        },
      ],
    },
    {
      title: "Comprehensive Data Security and Safeguards",
      intro:
        "The Company deploys institutional, physical, electronic, and administrative security protocols designed to safeguard your personal data from unauthorized access, alteration, catastrophic loss, data breaches, or unauthorized erasure.",
      items: [
        {
          label: "Technical Isolation",
          text: "Access to collected customer forms, technical log repositories, and network traffic data is partitioned behind strict multi-factor authentication walls and encrypted using high-grade Transport Layer Security (TLS/SSL) mechanisms during transmission over the internet.",
        },
        {
          label: "Statutory Breach Notification",
          text: "In the event of an accidental or malicious personal data breach affecting our servers, the Company will fulfill its obligations under applicable law by immediately notifying the respective authorities and all impacted Users in the legally mandated format.",
        },
        {
          label: "Disclaimer on Internet Vulnerability",
          text: "Despite our comprehensive defensive measures, you explicitly acknowledge that the transmission of data over the open internet or electronic data warehouses is never 100% secure. The Company cannot offer an absolute, airtight guarantee against advanced cyber-warfare, zero-day vulnerabilities, or targeted illicit network interventions.",
        },
      ],
    },
    {
      title: "Data Retention, Mandatory Erasure, and Absolute Exemptions for Derivative Data",
      items: [
        {
          label: "General Storage and Retention Scope",
          text: "The Company will retain your personal data strictly for the period necessary to fulfill the operational, commercial, technical, and analytical purposes outlined in Section 2 of this Policy, or as required to insulate the Company from legal risks and liability under Indian statute limitations.",
        },
        {
          label: "Strict Limitation on Data Erasure Rights",
          text: "While you retain the right to request the erasure of your personal data files, your right to demand such deletion is governed by absolute statutory restrictions and exceptions:",
        },
        {
          label: "Conditional Statutory Compliance Only",
          text: "In accordance with applicable laws, the Company will execute a data deletion request only if and to the minimum extent explicitly mandated by applicable law. If retention is required or permitted under any other statutory provision for the time being in force (such as tax compliance, vehicle transport regulations, corporate auditing requirements, or anti-fraud protocols), your deletion request will be legally rejected.",
        },
        {
          label: "The Irrevocability of Derivative Data, Algorithmic Weights, and Machine Learning Models",
          text: "For the absolute avoidance of doubt, any Derivative Data generated by the Company from processing your interactions is the exclusive, unchallengeable, and absolute proprietary property of the Company.",
        },
        {
          label: "Definition of Derivative Data",
          text: "Derivative Data includes, but is not limited to: high-level statistical aggregations, behavioral trends, de-identified metadata, machine learning training weights, algorithmic model adjustments, computer vision training sets, and data transformations developed or extracted by the Company's software engines from your interaction patterns.",
        },
        {
          label: "Survival of Derivations",
          text: 'Because Derivative Data does not constitute "personal data" under law (as an individual cannot be identified from an algorithmic weight or an aggregated trend), it cannot be deleted, wiped out, purged, or recalled upon your request. The Company maintains an absolute, permanent, and unconditional right to continue using, tweaking, exploiting, and commercializing all such Derivative Data in any form, manner, or medium, for any purpose whatsoever, indefinitely, and completely without your further permission, consent, or oversight.',
        },
      ],
    },
    {
      title: "Mandatory Compliance Grievance Redressal Desk",
      paragraphs: [
        "Any questions, access requests, erasure notices, or data-handling disputes must be directed privately to our designated grievance representative.",
        "By accepting these terms, you explicitly agree to submit any privacy concerns privately via this official channel. You are strictly prohibited from publishing public social media statements, online reviews, or tagging our official brand handles regarding any data dispute before allowing the Company to resolve it.",
      ],
      items: [
        { label: "Designated Grievance Officer", text: "[●]" },
        {
          label: "Corporate Desk Location",
          text: "EdgeVerse India Private Limited, G01, #520, 8th Cross BEML Layout, Thubarahalli, Bengaluru, Karnataka, India, Pin: 560066",
        },
        {
          label: "Electronic Communication Portal",
          text: "contact@edgeverse.ai",
        },
        {
          label: "Statutory Turnaround Resolution",
          text: "The Grievance Desk will investigate, log, and resolve your valid data concern within a maximum turnaround time of 30 (thirty) business days from the receipt of your official electronic mail.",
        },
      ],
    },
    {
      title: "Jurisdiction and Governing Law",
      paragraphs: [
        "This Privacy Policy, its structural interpretation, and any legal claims or disputes regarding data privacy between the User and the Company shall be governed by and construed exclusively in accordance with the laws of India, without regard to conflict of laws principles. Any legal proceedings or statutory disputes arising out of or relating to this Policy shall be subject to the exclusive jurisdiction of the competent courts located at Bengaluru, Karnataka, India.",
      ],
    },
    {
      title: "Cross-Border Transfers and Global Data Routing",
      paragraphs: [
        "The User explicitly acknowledges and agrees that the Company operates a distributed cloud architecture and globalized commercial network. To optimize the Website's latency, secure digital assets, and execute B2B analytics, personal data, technical logs, and passive metadata collected under this Policy may be transferred to, accessed from, routed through, and stored on secure external servers located outside the sovereign territory of India (including, but not limited to, data centers operated by Amazon Web Services, Google Cloud Platform, and Microsoft Azure). Further, the Company ensures that any such cross-border transfer of digital personal data shall be restricted or executed strictly in accordance with the blacklists, whitelists, or specific international data transfer frameworks and notifications issued by the Government of India from time to time. The User's consent granted herein serves as authorization to route such data across global jurisdictions, provided equivalent organizational security safeguards are maintained by our downstream Data Processors.",
      ],
    },
    {
      title: "Age Restrictions and Specific Exclusions",
      paragraphs: [
        "The Website, its underlying interfaces, and the B2B tech demonstrations hosted herein are strictly intended, engineered, and designed for use by enterprise professionals, commercial entities, and individuals who have attained the legal age of majority (18 years of age or older under the Indian Majority Act, 1875). The Company does not knowingly, intentionally, or systematically collect, log, or process digital personal data from children under the age of 18 or from persons with disabilities who have legal guardians. The Company maintains a zero-tolerance policy for child data tracking. If it is brought to our notice that a minor has circumvented our platform protocols and submitted data through our communication gateways, such data shall be permanently purged from our operational repositories immediately. Under no circumstances shall the Company engage in any processing of personal data that is likely to cause any detrimental effect on the well-being of a child, nor shall we engage in tracking, behavioral monitoring, or targeted marketing/advertising directed at children.",
      ],
    },
    {
      title: "Statutory Disclosure and Transfer to Third-Party Data Processors",
      paragraphs: [
        "The Company does not sell individual personal data profiles to brokers. However, to execute the processing operations outlined in Section 2, the User grants the Company the right to share or disclose specific granular datasets with vetted third-party data processors and cloud partners bound by strict confidentiality covenants. These disclosures are strictly confined to the following structural pillars:",
      ],
    },
    {
      title: "Commercial Communications and Right to Opt-Out",
      paragraphs: [
        "By submitting your corporate contact credentials via the Website, you explicitly consent to receive transactional electronic mail, B2B pilot proposals, system updates, and specialized corporate outreach from the Company's business development desks.",
        'The User maintains an absolute Right to Opt-Out from receiving promotional or marketing communications at any subsequent historical point. You may exercise this right by utilizing the designated "Unsubscribe" hyperlink embedded within any electronic mail dispatch transmitted by the Company, or by issuing a direct, formal "Opt-Out" directive to contact@edgeverse.ai. Upon verification, the Company will remove your contact coordinates from active promotional pipelines within seven (7) business days, without degrading your access to the public-facing aspects of the Website.',
      ],
    },
    {
      title: "Mandatory Duties and Statutory Penalties of the Users",
      paragraphs: [
        "The Users are hereby put on strict statutory notice that your rights under applicable law are bound by reciprocal Duties under applicable laws. By interacting with this Website, you solemnly declare and agree that you shall: (a) not suppress or misrepresent any material information while communicating with the Company; (b) not impersonate any other individual or entity while filling out contact configurations; (c) not register false, frivolous, or vexatious grievances or complaints with the Company. Any User who breaches these statutory duties or files demonstrably false or bad-faith complaints is legally liable to be penalized with a fine which may extend up to INR 10,000 (Rupees Ten Thousand) per infraction.",
      ],
    },
    {
      title: "Severability and Integrity of the Policy",
      paragraphs: [
        "This Privacy Policy constitutes the entire, integrated agreement and legal understanding between the User and the Company regarding digital personal data protection, privacy parameters, and informational processing on this Website. If any clause, provision, paragraph, or sub-section of this Policy is determined by a court of competent jurisdiction, a statutory tribunal, or any Board to be illegal, invalid, void, unconstitutional, or unenforceable under prevailing laws such determination shall be isolated. The invalidity of such specific clause shall not affect, impair, or invalidate the remaining portions of this Privacy Policy, and all other clauses shall remain in full force, effect, and operational validity.",
      ],
    },
    {
      title: "Amendments to This Policy",
      paragraphs: [
        "The Company reserves the unilateral right to amend, update, alter, or completely overhaul this Privacy Policy at its sole discretion at any time without prior individual notice to the Users. Any modifications will become effective immediately upon being posted to this URL on the Website. Your continued browsing or utilization of the Website following any update constitutes your binding, unconditional acceptance of the revised Privacy Policy.",
      ],
    },
  ],
};
