export { default as Home } from "./home/Home"
export { default as About } from "./about/About"
export { default as Career } from "./careers/Career"
export { default as Parent } from "./parent/Parent"
export { default as Technology } from "./technology/Technology"
export { default as Industries } from "./industries/Industries"
export { default as Safety } from "./safety/Safety"
export { default as Contact } from "./contact/Contact"